#!/usr/bin/env python
#--------------------------------------------------
# ECE 2524 Homework 3 Problem 1 Shaishav Parekh
# 
# Date: 09/16/2012
#--------------------------------------------------

import argparse
import fileinput
float list a = []
def mul(a):
	prod = 1
	for n in a:
		prod *= n
		res = ('%f' % prod).rstrip('0').rstrip('.')
	return res
	
for line in fileinput.input():
	a.append(line)
	mul(a)

parser.add_argument(dest='multiply', action='store_const', const=mul, help='multiply the integers.')
args = parser.parse_args()
print(args.multiply(args.numbers))

